// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x5n9pjkHvzguzBipVWhAiz
// Component: Mc0VBpijIxyn

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseCheckboxGroup } from "@plasmicpkgs/react-aria/skinny/registerCheckboxGroup";
import CoreLabel from "../../CoreLabel"; // plasmic-import: ToRnt6m7Pbw7/component
import CoreCheckbox from "../../CoreCheckbox"; // plasmic-import: D_XHct9FBU8q/component
import CoreDescription from "../../CoreDescription"; // plasmic-import: Kw7q__mVGhml/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: x5n9pjkHvzguzBipVWhAiz/projectcss
import sty from "./PlasmicCoreCheckboxGroup.module.css"; // plasmic-import: Mc0VBpijIxyn/css

createPlasmicElementProxy;

export type PlasmicCoreCheckboxGroup__VariantMembers = {};
export type PlasmicCoreCheckboxGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicCoreCheckboxGroup__VariantsArgs;
export const PlasmicCoreCheckboxGroup__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCoreCheckboxGroup__ArgsType = {
  defaultValues?: any;
  showLabel?: boolean;
  showDescription?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  onChange?: (val: any) => void;
  label?: React.ReactNode;
  options?: React.ReactNode;
  description?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCoreCheckboxGroup__ArgsType;
export const PlasmicCoreCheckboxGroup__ArgProps = new Array<ArgPropType>(
  "defaultValues",
  "showLabel",
  "showDescription",
  "disabled",
  "ariaLabel",
  "onChange",
  "label",
  "options",
  "description"
);

export type PlasmicCoreCheckboxGroup__OverridesType = {
  ariaCheckboxGroup?: Flex__<typeof BaseCheckboxGroup>;
  coreLabel?: Flex__<typeof CoreLabel>;
  coreDescription?: Flex__<typeof CoreDescription>;
};

export interface DefaultCoreCheckboxGroupProps {
  defaultValues?: any;
  showLabel?: boolean;
  showDescription?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  onChange?: (val: any) => void;
  label?: React.ReactNode;
  options?: React.ReactNode;
  description?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCoreCheckboxGroup__RenderFunc(props: {
  variants: PlasmicCoreCheckboxGroup__VariantsArgs;
  args: PlasmicCoreCheckboxGroup__ArgsType;
  overrides: PlasmicCoreCheckboxGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          showLabel: true,
          showDescription: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaCheckboxGroup.value",
        type: "readonly",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props["defaultValues"],

        onChangeProp: "onChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    disabled: false,
    readonly: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseCheckboxGroup
      data-plasmic-name={"ariaCheckboxGroup"}
      data-plasmic-override={overrides.ariaCheckboxGroup}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.ariaCheckboxGroup
      )}
      defaultValue={args.defaultValues}
      isDisabled={args.disabled}
      isReadOnly={$ccVariants["readonly"] ? true : undefined}
      onChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["ariaCheckboxGroup", "value"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
      value={generateStateValueProp($state, ["ariaCheckboxGroup", "value"])}
    >
      {$props.showLabel ? (
        <CoreLabel
          data-plasmic-name={"coreLabel"}
          data-plasmic-override={overrides.coreLabel}
          className={classNames("__wab_instance", sty.coreLabel)}
        >
          {renderPlasmicSlot({
            defaultContents: "Label",
            value: args.label
          })}
        </CoreLabel>
      ) : null}
      {renderPlasmicSlot({
        defaultContents: (
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__kTPz)}
          >
            <CoreCheckbox
              className={classNames("__wab_instance", sty.coreCheckbox__qoO01)}
              label={"Option 1"}
              value={"option1"}
            />

            <CoreCheckbox
              className={classNames("__wab_instance", sty.coreCheckbox__duIz5)}
              label={"Option 2"}
              value={"option2"}
            />

            <CoreCheckbox
              className={classNames("__wab_instance", sty.coreCheckbox__u0Vu2)}
              label={"Option 3"}
              value={"option3"}
            />
          </Stack__>
        ),
        value: args.options
      })}
      {$props.showDescription ? (
        <CoreDescription
          data-plasmic-name={"coreDescription"}
          data-plasmic-override={overrides.coreDescription}
          className={classNames("__wab_instance", sty.coreDescription)}
        >
          {renderPlasmicSlot({
            defaultContents: "Description...",
            value: args.description
          })}
        </CoreDescription>
      ) : null}
    </BaseCheckboxGroup>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaCheckboxGroup: ["ariaCheckboxGroup", "coreLabel", "coreDescription"],
  coreLabel: ["coreLabel"],
  coreDescription: ["coreDescription"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaCheckboxGroup: typeof BaseCheckboxGroup;
  coreLabel: typeof CoreLabel;
  coreDescription: typeof CoreDescription;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCoreCheckboxGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCoreCheckboxGroup__VariantsArgs;
    args?: PlasmicCoreCheckboxGroup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCoreCheckboxGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCoreCheckboxGroup__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCoreCheckboxGroup__ArgProps,
          internalVariantPropNames: PlasmicCoreCheckboxGroup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCoreCheckboxGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaCheckboxGroup") {
    func.displayName = "PlasmicCoreCheckboxGroup";
  } else {
    func.displayName = `PlasmicCoreCheckboxGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicCoreCheckboxGroup = Object.assign(
  // Top-level PlasmicCoreCheckboxGroup renders the root element
  makeNodeComponent("ariaCheckboxGroup"),
  {
    // Helper components rendering sub-elements
    coreLabel: makeNodeComponent("coreLabel"),
    coreDescription: makeNodeComponent("coreDescription"),

    // Metadata about props expected for PlasmicCoreCheckboxGroup
    internalVariantProps: PlasmicCoreCheckboxGroup__VariantProps,
    internalArgProps: PlasmicCoreCheckboxGroup__ArgProps
  }
);

export default PlasmicCoreCheckboxGroup;
/* prettier-ignore-end */
